### Variáveis
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNWVkYTU1LTUwMTUtNDM4MS1hZjQ3LWY5MGIwYWI3YjgxYyIsIm5vbWVfY29tcGxldG8iOiJBZG1pbmlzdHJhZG9yIFNpc3RlbWEiLCJlbWFpbCI6ImFkbWluQHNpc3RlbWEuY29tIiwidXJsX2ltYWdlbV9wZXJmaWwiOm51bGwsInBlcmZpcyI6W3sibm9tZSI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNzb2VzIjpbIlZpc3VhbGl6YXIgUmVsYXTDs3Jpb3MiLCJDcmlhciBVc3XDoXJpb3MiLCJFZGl0YXIgVXN1w6FyaW9zIiwiRXhjbHVpciBDb21lbnTDoXJpb3MiXX1dLCJpYXQiOjE3Mzc1NTU5NDQsImV4cCI6MTczODg1MTk0NH0.4AlIdhNmxO2EQ2SIC9e2ThmhQvvljAPxe0enPnyaZqM

@perfilId = ab856b86-8bfa-4a53-a6fd-87872d36e903

@id = adicionar-comentarios

### Buscar todas permissões
GET http://localhost:4000/permissao/todas
Authorization: Bearer {{token}}

### Buscar permissões por perfil
GET http://localhost:4000/permissao/{{perfilId}}
Authorization: Bearer {{token}}

### Salvar permissão
POST http://localhost:4000/permissao/salvar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Adicionar Comentários",
    "descricao": "Permite adicionar comentários no sistema."
}

### Buscar permissão por id
GET http://localhost:4000/permissao/{{id}}
Authorization: Bearer {{token}}