### Variáveis
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkYjRiZjdjLWE3NmUtNDM4OS05NTU2LThmMjgyZjY5ZDJmZiIsIm5vbWVfY29tcGxldG8iOiJKb8OjbyBkYSBTaWx2YSIsImVtYWlsIjoiakBtYWlsLmNvbSIsInRlbGVmb25lIjoiIiwidXJsX2ltYWdlbV9wZXJmaWwiOiIiLCJwZXJmaXMiOltdLCJwZXJtaXNzb2VzIjpbXSwiaWF0IjoxNzM4MjYwNDY5LCJleHAiOjE3Mzk1NTY0Njl9.73hIXQGilK_uGcA1uiUbf2CMMEmzxSBE-VtCrwqdaLw

@email = j@mail.com

@usuarioId = a3b47e7c-41e7-4353-b1d9-923a13840dfe

@perfisIds = ["925ed89e-fa3a-421c-a430-ced087d4b29f"]

### Listar todos os usuários
GET http://localhost:4000/usuario/todos
Authorization: Bearer {{token}}

### Buscar usuário por email
GET http://localhost:4000/usuario/email/{{email}}   
Authorization: Bearer {{token}}

### Relacionar usuário com Perfil
POST http://localhost:4000/usuario/relacionar-perfis
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "usuarioId": "{{usuarioId}}",
    "perfisIds": {{perfisIds}}
}

### Remover usuário
DELETE http://localhost:4000/usuario/deletar/{{email}}
Authorization: Bearer {{token}}

### Atualizar usuário
PUT http://localhost:4000/usuario/atualizar/{{email}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome_completo": "João da S.",
    "email": "joao@email.com",
    "url_imagem_perfil": "https://www.google.com.br",
    "horas_trabalho": "08:00 - 18:00",
    "dias_trabalho": "Seg,Ter,Qua,",
    "telefone": "(11) 99999-9999"
}