### Variáveis
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlOTc3NDhlLWQ0MjgtNDExYi1iMjYwLTU3OWVmMTllZGU2ZiIsIm5vbWVfY29tcGxldG8iOiJBZG1pbmlzdHJhZG9yIFNpc3RlbWEiLCJlbWFpbCI6ImFkbWluQHNpc3RlbWEuY29tIiwidXJsX2ltYWdlbV9wZXJmaWwiOm51bGwsInBlcmZpcyI6W3sibm9tZSI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNzb2VzIjpbIlZpc3VhbGl6YXIgUmVsYXTDs3Jpb3MiLCJDcmlhciBVc3XDoXJpb3MiLCJFZGl0YXIgVXN1w6FyaW9zIiwiRXhjbHVpciBDb21lbnTDoXJpb3MiXX1dLCJpYXQiOjE3Mzc4MjQyMzAsImV4cCI6MTczOTEyMDIzMH0.VwJmAK4dfjKJCjZXN1M4Z-DJeXdWbunrqTTZsJoaN8I

@email = joao@email.com

@usuarioId = aa99632c-2748-49bd-99f8-58cbd99efce9

@perfisIds = ["925ed89e-fa3a-421c-a430-ced087d4b29f"]

### Registrar usuário
POST http://localhost:4000/usuario/registrar
Content-Type: application/json

{
    "nome_completo": "João da Silva",
    "email": "joao@email.com",
    "senha": "123456"
}

### Login
POST http://localhost:4000/usuario/login
Content-Type: application/json

{
    "email": "admin@sistema.com",
    "senha": "#Senha123"
}

### Listar todos os usuários
GET http://localhost:4000/usuario/todos
Authorization: Bearer {{token}}

### Buscar usuário por email
GET http://localhost:4000/usuario/email/{{email}}   
Authorization: Bearer {{token}}

### Relacionar usuário com Perfil
POST http://localhost:4000/usuario/relacionar-perfis
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "usuarioId": "{{usuarioId}}",
    "perfisIds": {{perfisIds}}
}

### Remover usuário
DELETE http://localhost:4000/usuario/deletar/{{usuarioId}}

### Atualizar usuário
PUT http://localhost:4000/usuario/atualizar/{{email}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome_completo": "João da S.",
    "email": "joao@email.com",
    "senha": "!Senha123",
    "url_imagem_perfil": "https://www.google.com.br",
    "horas_trabalho": "08:00 - 18:00",
    "dias_trabalho": "Seg,Ter,Qua,",
    "telefone": "(11) 99999-9999"
}