### Variáveis
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ZGYxMjM4LThiMzgtNGNlMi05MWVjLTM2ZWE2MzAzYzg5NyIsIm5vbWVfY29tcGxldG8iOiJBZG1pbmlzdHJhZG9yIFNpc3RlbWEiLCJlbWFpbCI6ImFkbWluQHNpc3RlbWEuY29tIiwidXJsX2ltYWdlbV9wZXJmaWwiOm51bGwsInBlcmZpcyI6W3sibm9tZSI6IkFkbWluaXN0cmFkb3IiLCJwZXJtaXNzb2VzIjpbIlZpc3VhbGl6YXIgUmVsYXTDs3Jpb3MiXX1dLCJpYXQiOjE3Mzc3MjMxOTUsImV4cCI6MTczOTAxOTE5NX0.qywGTfFvBFAhOTjS7CDJripQ4oodJ7UEMLkdcyf7FoQ

### Registrar usuário
POST http://localhost:4000/usuario/registrar
Content-Type: application/json

{
    "nome_completo": "João da Silva",
    "email": "joao@email.com",
    "senha": "123456"
}

### Login
POST http://localhost:4000/usuario/login
Content-Type: application/json

{
    "email": "admin@sistema.com",
    "senha": "#Senha123"
}

### Listar todos os usuários
GET http://localhost:4000/usuario/todos
Authorization: Bearer {{token}}