import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { ProvedorSessao } from "@/data/contexts/ContextoSessao";
import { ProvedorMensagem } from "@/data/contexts/ContextoMensagem";
import Mensagens from "@/components/shared/Mensagem";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR">
      <body className={poppins.className}>
        <ProvedorMensagem>
          <ProvedorSessao>
            {children}
            <Mensagens />
          </ProvedorSessao>
        </ProvedorMensagem>
      </body>
    </html>
  );
}
